// apps/dashboard-react/src/app/features/admin/AdminDashboard.tsx
import { useEffect } from 'react';
import { useAdmin } from '../../hooks/useAdmin';
import { StatCard } from '../../components/ui/StatCard';
import { Button } from '../../components/ui/Button';
import { Link } from 'react-router-dom';
import { Loader2, Plus, BarChart3 } from 'lucide-react';

export function AdminDashboard() {
    const { stats, loading, error, loadStats } = useAdmin();

    useEffect(() => {
        loadStats();
    }, [loadStats]);

    if (loading && !stats) {
        return (
            <div className="flex h-64 items-center justify-center">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
            </div>
        );
    }

    if (error) {
        return (
            <div className="p-6 text-center bg-destructive/10 text-destructive rounded-lg">
                {error}
            </div>
        );
    }

    if (!stats) return null;

    return (
        <div className="space-y-8 animate-in fade-in duration-500">
            <h1 className="text-3xl font-bold tracking-tight">Admin Dashboard</h1>

            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">
                <StatCard
                    title="Organizations"
                    value={stats.organizations.total}
                    suffix={`${stats.organizations.active} active`}
                    icon="&#127970;"
                />
                <StatCard
                    title="Users"
                    value={stats.users.total}
                    icon="&#128101;"
                />
                <StatCard
                    title="Forms"
                    value={stats.forms.total}
                    icon="&#128196;"
                />
                <StatCard
                    title="Submissions"
                    value={stats.submissions.total}
                    suffix={`${stats.submissions.last30Days} last 30 days`}
                    icon="&#128203;"
                />
            </div>

            <div className="space-y-4">
                <h2 className="text-xl font-semibold">Quick Actions</h2>
                <div className="flex flex-wrap gap-4">
                    <Button asChild>
                        <Link to="/admin/organizations">
                            <Plus className="mr-2 h-4 w-4" />
                            Create Organization
                        </Link>
                    </Button>
                    <Button variant="outline" asChild>
                        <Link to="/admin/submissions">
                            <BarChart3 className="mr-2 h-4 w-4" />
                            View All Submissions
                        </Link>
                    </Button>
                </div>
            </div>
        </div>
    );
}

// apps/dashboard-ui/src/app/features/admin/admin-dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { StatCardComponent } from '../../shared/components/stat-card.component';
import { AdminService, AdminStats } from '../../services/admin.service';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule, RouterLink, StatCardComponent],
  template: `
    <div class="admin-dashboard">
      <h1 class="page-title">Admin Dashboard</h1>

      <div class="loading" *ngIf="loading">Loading statistics...</div>
      <div class="error" *ngIf="error">{{ error }}</div>

      <div class="stats-grid" *ngIf="stats">
        <app-stat-card
          title="Organizations"
          [value]="stats.organizations.total"
          [suffix]="stats.organizations.active + ' active'"
          icon="&#127970;"
        ></app-stat-card>

        <app-stat-card
          title="Users"
          [value]="stats.users.total"
          icon="&#128101;"
        ></app-stat-card>

        <app-stat-card
          title="Forms"
          [value]="stats.forms.total"
          icon="&#128196;"
        ></app-stat-card>

        <app-stat-card
          title="Submissions"
          [value]="stats.submissions.total"
          [suffix]="stats.submissions.last30Days + ' last 30 days'"
          icon="&#128203;"
        ></app-stat-card>
      </div>

      <div class="quick-actions" *ngIf="!loading">
        <h2>Quick Actions</h2>
        <div class="action-buttons">
          <a routerLink="/admin/organizations" class="action-btn">
            <span>&#10133;</span> Create Organization
          </a>
          <a routerLink="/admin/submissions" class="action-btn">
            <span>&#128200;</span> View All Submissions
          </a>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .admin-dashboard { max-width: 1200px; }

    .page-title {
      font-size: 1.75rem;
      font-weight: 600;
      color: #1f2937;
      margin: 0 0 24px 0;
    }

    .loading, .error {
      padding: 20px;
      text-align: center;
      background: #fff;
      border-radius: 12px;
      border: 1px solid #e5e7eb;
    }

    .error { color: #dc2626; background: #fef2f2; }

    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 20px;
      margin-bottom: 32px;
    }

    .quick-actions h2 {
      font-size: 1.1rem;
      font-weight: 600;
      color: #1f2937;
      margin: 0 0 16px 0;
    }

    .action-buttons {
      display: flex;
      gap: 12px;
      flex-wrap: wrap;
    }

    .action-btn {
      display: inline-flex;
      align-items: center;
      gap: 8px;
      padding: 12px 20px;
      background: #1f2937;
      color: #fff;
      text-decoration: none;
      border-radius: 8px;
      font-weight: 500;
      font-size: 0.9rem;
      transition: background 0.15s;
    }

    .action-btn:hover { background: #374151; }
  `]
})
export class AdminDashboardComponent implements OnInit {
  stats: AdminStats | null = null;
  loading = true;
  error = '';

  constructor(private adminService: AdminService) {}

  async ngOnInit() {
    try {
      this.stats = await this.adminService.getStats();
    } catch (err: any) {
      this.error = err.message || 'Failed to load statistics';
    } finally {
      this.loading = false;
    }
  }
}
