// apps/dashboard-ui/src/app/shared/ui/table.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { cn } from './utils';

/**
 * Table Components - Spartan UI Style
 *
 * Usage:
 * <ui-table>
 *   <ui-table-header>
 *     <ui-table-row>
 *       <ui-table-head>Name</ui-table-head>
 *       <ui-table-head>Email</ui-table-head>
 *     </ui-table-row>
 *   </ui-table-header>
 *   <ui-table-body>
 *     <ui-table-row>
 *       <ui-table-cell>John</ui-table-cell>
 *       <ui-table-cell>john@example.com</ui-table-cell>
 *     </ui-table-row>
 *   </ui-table-body>
 * </ui-table>
 */

@Component({
  selector: 'ui-table',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="relative w-full overflow-auto">
      <table [class]="getTableClasses()">
        <ng-content></ng-content>
      </table>
    </div>
  `,
  styles: []
})
export class TableComponent {
  @Input() class = '';

  getTableClasses(): string {
    return cn('w-full caption-bottom text-sm', this.class);
  }
}

@Component({
  selector: 'ui-table-header',
  standalone: true,
  template: `
    <thead class="[&_tr]:border-b">
      <ng-content></ng-content>
    </thead>
  `,
  styles: []
})
export class TableHeaderComponent {}

@Component({
  selector: 'ui-table-body',
  standalone: true,
  template: `
    <tbody class="[&_tr:last-child]:border-0">
      <ng-content></ng-content>
    </tbody>
  `,
  styles: []
})
export class TableBodyComponent {}

@Component({
  selector: 'ui-table-footer',
  standalone: true,
  template: `
    <tfoot class="border-t bg-muted/50 font-medium [&>tr]:last:border-b-0">
      <ng-content></ng-content>
    </tfoot>
  `,
  styles: []
})
export class TableFooterComponent {}

@Component({
  selector: 'ui-table-row',
  standalone: true,
  imports: [CommonModule],
  template: `
    <tr [class]="getRowClasses()">
      <ng-content></ng-content>
    </tr>
  `,
  styles: []
})
export class TableRowComponent {
  @Input() class = '';

  getRowClasses(): string {
    return cn(
      'border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted',
      this.class
    );
  }
}

@Component({
  selector: 'ui-table-head',
  standalone: true,
  imports: [CommonModule],
  template: `
    <th [class]="getHeadClasses()">
      <ng-content></ng-content>
    </th>
  `,
  styles: []
})
export class TableHeadComponent {
  @Input() class = '';

  getHeadClasses(): string {
    return cn(
      'h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0',
      this.class
    );
  }
}

@Component({
  selector: 'ui-table-cell',
  standalone: true,
  imports: [CommonModule],
  template: `
    <td [class]="getCellClasses()">
      <ng-content></ng-content>
    </td>
  `,
  styles: []
})
export class TableCellComponent {
  @Input() class = '';

  getCellClasses(): string {
    return cn('p-4 align-middle [&:has([role=checkbox])]:pr-0', this.class);
  }
}

@Component({
  selector: 'ui-table-caption',
  standalone: true,
  template: `
    <caption class="mt-4 text-sm text-muted-foreground">
      <ng-content></ng-content>
    </caption>
  `,
  styles: []
})
export class TableCaptionComponent {}

// apps/dashboard-react/src/app/components/ui/Table.tsx
import * as React from "react"
import { cn } from "../../../lib/utils"

const Table = React.forwardRef<
    HTMLTableElement,
    React.HTMLAttributes<HTMLTableElement>
>(({ className, ...props }, ref) => (
    <div className="relative w-full overflow-auto">
        <table
            ref={ref}
            className={cn("w-full caption-bottom text-sm", className)}
            {...props}
        />
    </div>
))
Table.displayName = "Table"

const TableHeader = React.forwardRef<
    HTMLTableSectionElement,
    React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
    <thead ref={ref} className={cn("[&_tr]:border-b", className)} {...props} />
))
TableHeader.displayName = "TableHeader"

const TableBody = React.forwardRef<
    HTMLTableSectionElement,
    React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
    <tbody
        ref={ref}
        className={cn("[&_tr:last-child]:border-0", className)}
        {...props}
    />
))
TableBody.displayName = "TableBody"

const TableFooter = React.forwardRef<
    HTMLTableSectionElement,
    React.HTMLAttributes<HTMLTableSectionElement>
>(({ className, ...props }, ref) => (
    <tfoot
        ref={ref}
        className={cn(
            "border-t bg-muted/50 font-medium [&>tr]:last:border-b-0",
            className
        )}
        {...props}
    />
))
TableFooter.displayName = "TableFooter"

const TableRow = React.forwardRef<
    HTMLTableRowElement,
    React.HTMLAttributes<HTMLTableRowElement>
>(({ className, ...props }, ref) => (
    <tr
        ref={ref}
        className={cn(
            "border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted",
            className
        )}
        {...props}
    />
))
TableRow.displayName = "TableRow"

const TableHead = React.forwardRef<
    HTMLTableCellElement,
    React.ThHTMLAttributes<HTMLTableCellElement>
>(({ className, ...props }, ref) => (
    <th
        ref={ref}
        className={cn(
            "h-10 px-2 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[0.5px]",
            className
        )}
        {...props}
    />
))
TableHead.displayName = "TableHead"

const TableCell = React.forwardRef<
    HTMLTableCellElement,
    React.TdHTMLAttributes<HTMLTableCellElement>
>(({ className, ...props }, ref) => (
    <td
        ref={ref}
        className={cn(
            "p-2 align-middle [&:has([role=checkbox])]:pr-0 [&>[role=checkbox]]:translate-y-[0.5px]",
            className
        )}
        {...props}
    />
))
TableCell.displayName = "TableCell"

const TableCaption = React.forwardRef<
    HTMLTableCaptionElement,
    React.HTMLAttributes<HTMLTableCaptionElement>
>(({ className, ...props }, ref) => (
    <caption
        ref={ref}
        className={cn("mt-4 text-sm text-muted-foreground", className)}
        {...props}
    />
))
TableCaption.displayName = "TableCaption"

export {
    Table,
    TableHeader,
    TableBody,
    TableFooter,
    TableHead,
    TableRow,
    TableCell,
    TableCaption,
}
